version: '3.6'
services:
  # MongoDB Replica Set
  mongo1:
    image: "mongo:4.0-xenial"
    hostname: localhost    
    container_name: mongo1
    # command: --replSet rs0 --smallfiles --oplogSize 128
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - rs1:/data/db
    networks:
      - intuit
    ports:
      - "27017:27017"
    restart: always
  
  mongo2:
    image: "mongo:4.0-xenial"
    hostname: localhost    
    container_name: mongo2
    #command: --replSet rs0 --smallfiles --oplogSize 128
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - rs2:/data/db
    networks:
      - intuit   
    ports:
      - "27018:27017"
    restart: always
    
  mongo3:
    image: "mongo:4.0-xenial"
    hostname: localhost    
    container_name: mongo3
    #command: --replSet rs0 --smallfiles --oplogSize 128
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - rs3:/data/db
    networks:
      - intuit   
    ports:
      - "27019:27017"
    restart: always

networks:
  intuit:
    driver: bridge
   # attachable: true

volumes:
  rs1:
  rs2:
  rs3: